### ISSUE TITLE
[Bug] Youtube Account Login not working.

### ISSUE THREAD

**Issue by ProRedHD** [dennisfischer/simplejavayoutubeuploader#11]
Hey,

I don't know if this repo is still being updated. I can't use the Simple Youtube Uploader because if I type my account email and password in. It loades forever and nothing is happening.

I hope you read this because the Uploader is a really cool program and lots of people can't use it :(
-ProRed

**Comment by telepath** [comment]
Yes @dennisfischer, please fix it, it's the only comfortable way to upload youtube videos I know :)

**Comment by klonamy** [comment]
Yeah it is nice to have that programm.

**Comment by inpothet** [comment]
The reason the login is not working is because he used API V2
sadly it got discontinued and the program has to be rewritten as some features were lost in v3

**Comment by dennisfischer** [comment]
Login is only possible with OAuth now.
