### ISSUE TITLE
What API version was used

### ISSUE THREAD

**Issue by nekocentral** [dennisfischer/simplejavayoutubeuploader#12]
What version of the api did you use
is ig Data api V3 compacatable ?

**Comment by dennisfischer** [comment]
Mostly v2 was used which got deprecated. A switch to v3 creates many new problems. V3 is missing 90% features, which you then have to recreate somehow. The only possible way is to do the http requests manually, which is a really dirty hack. You basically need full account permissions (typically all necessary cookies) and even then you got no guarantee, that your request succeeds. Additionally V3 gives you a lot of problems with resumable uploading as you only got a few seconds to resume your upload before it fails. V2 was more lenient and gave you several hours / days.

**Comment by inpothet** [comment]
but as far as i know and have seen you can upload videos and do all old things expect monitization using the v3 api

**Comment by dennisfischer** [comment]
That's not true. Many features are missing. Just take a look at: https://developers.google.com/youtube/v3/docs/videos/insert and you'll see, that many options - options that were available in v2 and options that are available on youtubes website - are missing.
